version: "3.8"

services:
  app:
    image: ghcr.io/yourusername/terminal-portfolio:latest
    # Alternatively, build from local Dockerfile
    # build:
    #   context: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=portfolio
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - mongodb
    restart: unless-stopped
    # Set resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
